devtools::install_github("cysouw/qlcMatrix", upgrade = FALSE)
install.packages("DDRTree")
install.packages("densityClust")
BiocManager::install("monocle.objSingleCell", update = FALSE)
install.packages("fastICA")
BiocManager::install("biocViews", update = FALSE)
BiocManager::install("HSMMSingleCell", update = FALSE)
install.packages("/media/hieunguyen/HD01/storage/offline_pkgs/monocle_2.30.0/monocle", type = "source", repos = NULL)
BiocManager::install("tradeSeq", update = FALSE)