# remove.packages("monocle3")
devtools::install_github("cysouw/qlcMatrix", upgrade = FALSE)
install.packages("DDRTree")
install.packages("densityClust")
BiocManager::install("monocle.objSingleCell", update = FALSE)
install.packages("fastICA")
BiocManager::install("biocViews", update = FALSE)
BiocManager::install("HSMMSingleCell", update = FALSE)
install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/monocle_2.32.0.tar.gz", type = "source", repos = NULL)
BiocManager::install("tradeSeq", update = FALSE)
